add samples and documentation for accessLog programatic configuration
reactor/reactor-netty pull request #1452
Opened 2021-01-06 16:04 UTC by aneveu

2021-01-06 16:29 UTC, violetagg approved these changes

2021-01-06 16:49 UTC, Buzzardo requested changes

2021-01-06 16:49 UTC, Buzzardo commented on docs/asciidoc/http-server.adoc
> +The `HTTP` access log could be enabled programmatically or by configuration. By default, it is disabled.
Change the line to:

You can access the `HTTP` access either programmatically or by configuration. By default, it is disabled.

2021-01-06 16:49 UTC, Buzzardo commented on docs/asciidoc/http-server.adoc
> +Calling this method will take precedence over the system property configuration.
Change "will take" to "takes"

2021-01-06 16:49 UTC, Buzzardo commented on docs/asciidoc/http-server.adoc
> +specify a custom one as parameter like in the following example:
Change the line to:

specify a custom one as a parameter, as in the following example:

2021-01-06 16:49 UTC, Buzzardo commented on docs/asciidoc/http-server.adoc
> +You can also filter `HTTP` access logs using the `AccessLogFactory#createFilter` method, as in the following example:
Change "using" to "by using"

2021-01-06 17:27 UTC, violetagg requested changes

2021-01-06 17:27 UTC, violetagg commented on docs/asciidoc/http-server.adoc
> +Calling this method will takes precedence over the system property configuration.
Remove `will` from `will takes`

2021-01-07 10:51 UTC, violetagg approved these changes

2021-01-07 16:29 UTC, aneveu commented on docs/asciidoc/http-server.adoc
> +You can enable the `HTTP` access either programmatically or by configuration. By default, it is disabled.
thanks!

2021-01-07 17:45 UTC, simonbasle approved these changes

2021-01-08 09:17 UTC, merged