Extend the connection pool documentation
reactor/reactor-netty pull request #1648
Opened 2021-05-31 15:28 UTC by violetagg

Add examples for `HttpClient`

2021-05-31 15:59 UTC, simonbasle requested changes
suggested several improvements to the wording.

2021-05-31 15:59 UTC, simonbasle commented on docs/asciidoc/conn-provider.adoc
> +and `1000` as the maximum number of the registered requests for acquire to keep in the pending queue
```suggestion
By default, Reactor Netty client uses a "`fixed`" connection pool with `500` as the maximum number of active channels
and `1000` as the maximum number of further channel acquisition attempts allowed to be kept in a pending state
```

2021-05-31 15:59 UTC, simonbasle commented on docs/asciidoc/conn-provider.adoc
> +until a channel is returned to the pool again.
```suggestion
When the maximum number of channels in the pool is reached, up to 1000 new attempts to 
acquire a channel are delayed (pending) until a channel is returned to the pool again,
and further attempts are declined with an error. 
```

2021-05-31 15:59 UTC, simonbasle commented on docs/asciidoc/conn-provider.adoc
> +for a specified time, thus applicable for disposal. By default, the background disposal is disabled.
```suggestion
| `disposeInactivePoolsInBackground` | When this option is enabled, connection pools are regularly checked in the background
and those that are empty and been inactive for a specified time become eligible for disposal. By default, this background
disposal of inactive pools is disabled.
```

2021-05-31 15:59 UTC, simonbasle commented on docs/asciidoc/conn-provider.adoc
> +that are applicable for removal. By default, the background eviction is disabled.
```suggestion
| `evictInBackground` | When this option is enabled, each connection pool regularly checks for connections that are
eligible for removal according to eviction criteria like `maxIdleTime`. By default, this background eviction is disabled.
```

2021-05-31 15:59 UTC, simonbasle commented on docs/asciidoc/conn-provider.adoc
> +| `maxLifeTime` | The time after which the channel will be closed (resolution: ms). Default: max lifetime is not specified.
```suggestion
| `maxIdleTime` | The time after which the channel is eligible to be closed when idle (resolution: ms). Default: max idle time is not specified.
|`maxLifeTime` | The total life time after which the channel is eligible to be closed (resolution: ms). Default: max lifetime is not specified.
```

2021-05-31 15:59 UTC, simonbasle commented on docs/asciidoc/conn-provider.adoc
> +If -1 is specified, the pending queue does not have upper limit. Default to 2 * max connections.
```suggestion
| `pendingAcquireMaxCount` | The maximum number of extra attempts at acquiring a connection to keep in a pending queue.
If -1 is specified, the pending queue does not have upper limit. Default to 2 * max connections.
```

2021-05-31 15:59 UTC, simonbasle commented on docs/asciidoc/conn-provider.adoc
> +connection in an unbounded fashion. Default: 45 seconds.
```suggestion
| `pendingAcquireTimeout` | The maximum time before which a pending acquire must complete, or a TimeoutException is
thrown (resolution: ms). If -1 is specified, no such timeout is applied. Default: 45 seconds.
```

2021-05-31 15:59 UTC, simonbasle commented on docs/asciidoc/conn-provider.adoc
> +This means that the implementation creates a new channel if someone tries to acquire a channel but none is in the pool.
```suggestion
This means that the implementation creates a new channel if someone tries to acquire a channel as long as less than 500 have been created and are managed by the pool.
```

2021-05-31 17:16 UTC, violetagg commented
@simonbasle Please check the new changes

2021-06-01 09:06 UTC, simonbasle approved these changes

2021-06-01 10:46 UTC, merged

2021-06-01 10:47 UTC, violetagg commented
@simonbasle Thanks for the review