Issue-1665: StringIndexOutOfBoundsException when using directory route
reactor/reactor-netty pull request #1666
Opened 2021-06-13 18:24 UTC by roggenbrot

Original issue: #1665 

This PR fixes the `StringIndexOutOfBoundsException` by checking the length of the string before accessing char 0

2021-06-14 08:40 UTC, violetagg requested changes
Please fix the errors/warnings from the build https://github.com/reactor/reactor-netty/runs/2817916849?check_suite_focus=true#step:5:124

2021-06-15 07:55 UTC, violetagg approved these changes

2021-06-15 07:56 UTC, violetagg commented
@reactor/netty-team PTAL

2021-06-15 07:59 UTC, simonbasle approved these changes

2021-06-15 08:03 UTC, merged

2021-06-15 08:04 UTC, violetagg commented
@roggenbrot Thanks for the PR!