Simple code refactor: functions logic, repetitive messages, throws catching.
reactor/reactor-netty pull request #1824
Opened 2021-09-25 01:53 UTC by Jhooomn

updated: it was used sonar-lint plugin for this pull request; mainly purpose is to reduce complexity or redundant piece of code inside classes... for example like:

- common string messages
- didn't use assertThat functions and create same logic
- catch throwable instead of exceptions

2021-09-25 01:53 UTC, pivotal-cla commented
@Jhooomn Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1824)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1824) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-09-25 01:54 UTC, pivotal-cla commented
@Jhooomn Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1824)!

2021-09-25 08:45 UTC, violetagg commented
@Jhooomn Please create PR for every type of issue i.e. one handling extraction of the strings, the other exception vs throwable etc.

2021-09-25 18:36 UTC, Jhooomn commented
@violetagg  I'll keep on mind for next PR's. Could you merge this one?

2021-09-26 14:22 UTC, violetagg requested changes

2021-09-26 14:22 UTC, violetagg commented on reactor-netty-core/src/jarFileTest/java/reactor/netty/JarFileShadingTest.java
> +	public static final String REACTOR_STRING = "reactor";
```suggestion
	static final String REACTOR_STRING = "reactor";
```

2021-09-26 14:22 UTC, violetagg commented on reactor-netty-core/src/jarFileTest/java/reactor/netty/JarFileShadingTest.java
> +				.filter(ze -> Objects.nonNull(ze) && Objects.nonNull(ze.getName()))
I'm not sure that this check is necessary. Wdyt?

2021-09-26 14:22 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/FutureMono.java
> +			catch (Exception t) {
catching `Throwable` is deliberate

2021-09-26 14:22 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/channel/AbortedException.java
> +	public static final String CONNECTION_RESET_BY_PEER_MESSAGE = "Connection reset by peer";
```suggestion
	static final String CONNECTION_RESET_BY_PEER_MESSAGE = "Connection reset by peer";
```

2021-09-26 14:22 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
> +		catch (Exception err) {
catching `Throwable` is deliberate

2021-09-26 14:22 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/channel/ChannelOperationsHandler.java
> +		catch (Exception err) {
catching `Throwable` is deliberate

2021-09-26 14:22 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java
> +							((ByteBuf) v).touch(format(channel, RECEIVER_MESSAGE + a.getClass().getName() +
In production where DEBUG is not enabled, these strings will not be created (guarded by `logLeakDetection.isDebugEnabled()`). If we convert these strings to a constants, then these constants will be created always regardless whether it is needed or not. Wdyt?

2021-09-26 14:22 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java
> -			//parent.listener.onReceiveError(channel, ex);
Please return this commented line

2021-09-26 14:22 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/channel/FluxReceive.java
> +					catch (Exception t) {
catching `Throwable` is deliberate

2021-09-26 18:39 UTC, closed without merging