#1872: Implement additional metrics from reactor-pool
reactor/reactor-netty pull request #1897
Opened 2021-11-25 18:19 UTC by pderop

Please review this PR, which adds two methods in the ConnectionPoolMetrics interface:

The added methods (maxAllocatedSize, and maxPendingAcquireSize) simply expose the delegated methods from the original InstrumentedPool.PoolMetrics. This will most likely resolve the #1872 issue.

2021-11-26 07:23 UTC, violetagg requested changes

2021-11-26 07:23 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionPoolMetrics.java
> +	 * A Pool might be unbounded, in which case this method returns Integer.MAX_VALUE.
nit:

```suggestion
	 * A Pool might be unbounded, in which case this method returns {@code Integer.MAX_VALUE}.
```

2021-11-26 07:23 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionPoolMetrics.java
> +	 * @return the maximum number of live resources that can be allocated by this Pool
Add `@since 1.0.14`
When a functionality is added after GA, we explicitly indicate in which version this functionality is added.

2021-11-26 07:23 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionPoolMetrics.java
> +	 * Get the maximum number of Pool.acquire() this Pool can queue in a pending state
nit:

```suggestion
	 * Get the maximum number of {@code Pool.acquire()} this Pool can queue in a pending state
```

2021-11-26 07:23 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionPoolMetrics.java
> +	 * Integer.MAX_VALUE.
nit:

```suggestion
	 * {@code Integer.MAX_VALUE}.
```

2021-11-26 07:23 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionPoolMetrics.java
> +	 * @return the maximum number of pending acquire that can be enqueued by this Pool
Add `@since 1.0.14`

2021-11-26 10:33 UTC, violetagg approved these changes

2021-11-26 10:33 UTC, violetagg commented
@reactor/netty-team PTAL

2021-11-27 18:23 UTC, epicoxymoron commented
If I'm understanding this PR correctly, the metrics wouldn't be pushed to Micrometer.  Correct me if I'm wrong, but wouldn't there need to also be changes [here](https://github.com/reactor/reactor-netty/blob/137cc47005c58dfbd375df62a9b0ba68760916c3/reactor-netty-core/src/main/java/reactor/netty/resources/MicrometerPooledConnectionProviderMeterRegistrar.java#L50)?

2021-11-29 11:34 UTC, pderop commented
@epicoxymoron , thanks for your comment, I have updated the PR in order to publish the added meters to Micrometers. Also updated the documentation.

2021-11-29 12:16 UTC, violetagg approved these changes

2021-11-29 14:30 UTC, epicoxymoron commented
This looks like it would solve my issue in #1872.  Thank you!

As a small nit, you may consider reusing the `@return` commentary from the [InstrumentedPool Javadocs](https://github.com/reactor/reactor-pool/blob/main/src/main/java/reactor/pool/InstrumentedPool.java) as the descriptions; personally I think it's a little more clear.

* .max.connections: the maximum number of live resources that can be allocated by this pool
* .max.pending.connections: the maximum number of pending acquire that can be enqueued by this pool

I'm not a member of the project team, but this has my approval with or without those changes.  Thank you again!

2021-11-29 15:48 UTC, simonbasle approved these changes

2021-11-29 16:59 UTC, pderop commented
I did not exactly copy the same descriptions from the reactor pool which is generic, but I slightly clarified the descriptions.

2021-11-29 17:22 UTC, violetagg approved these changes

2021-11-30 02:23 UTC, epicoxymoron commented
Verbiage LGTM.  You may want to propagate it to the docs + Javadocs on Metrics.java as well.

2021-11-30 09:30 UTC, violetagg approved these changes

2021-11-30 09:34 UTC, simonbasle approved these changes

2021-11-30 09:50 UTC, merged