Add a pre-screen before locking inside computeIfAbsent
reactor/reactor-netty pull request #1930
Opened 2021-12-12 16:01 UTC by zimatars

computeIfAbsent pessimistically locks instead of optimistically trying to return an existing entry.

2021-12-12 16:01 UTC, pivotal-cla commented
@zimatars Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1930)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1930) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-12-12 16:03 UTC, pivotal-cla commented
@zimatars Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-netty&pullRequestId=1930)!

2021-12-17 11:00 UTC, simonbasle commented
@zimatars @pderop has made some measurements, and from what I understand in newer versions of java there's an integrated pre-screen that is even better because it can accomodate parrallel deletions.

this particular map is not necessarily a great candidate for pre-screening that way, precisely because entries are regularly deleted from it (and the pre-screen isn't atomic)

there are however other instances in the code of reactor-netty where maps are more like pre-established dictionaries with very little deletion, which could benefit from your approach. Do you want to explore that in a separate PR?

@reactor/netty-team I don't think we can merge this one

2021-12-17 11:01 UTC, simonbasle requested changes
(see my comment above)
I'll delegate the final choice to @violetagg

2021-12-17 13:00 UTC, simonbasle commented
@zimatars, @violetagg is still thinking about whether or not to apply this PR, we'll keep you posted for that particular case.

2021-12-20 10:14 UTC, violetagg commented
@zimatars I'm going to accept this PR. Thanks a lot!

2021-12-20 10:15 UTC, violetagg approved these changes

2021-12-20 10:52 UTC, merged