Reduce memory overhead when creating Micrometer timers
reactor/reactor-netty pull request #2057
Opened 2022-02-24 11:39 UTC by pderop

The purpose of this PR is to reduce memory overhead when creating Micrometer timers instances.

2022-02-24 12:57 UTC, violetagg commented
Related to #1952

2022-03-02 09:41 UTC, violetagg commented on reactor-netty-http/src/main/java/reactor/netty/http/client/MicrometerHttpClientMetricsRecorder.java
> +	Timer getResponseTimeTimer(String name, String address, String uri, String method, String status) {
What do you think to make this `final`?

2022-03-02 16:25 UTC, pderop commented on reactor-netty-core/src/main/java/reactor/netty/transport/MicrometerAddressResolverGroupMetrics.java
> +			this.recorder = recorder;
I applied your feedbacks, thanks.

2022-03-04 11:54 UTC, violetagg commented
Rebased in order to pick up #2070

2022-03-04 12:57 UTC, pderop commented
there is a compile issue, the main branch does not seem to compile ?

> Task :reactor-netty-core:compileJava
/Users/pderop/Work/projects/reactor-netty-pderop/reactor-netty-core/src/main/java/reactor/netty/transport/ByteBufAllocatorMetrics.java:18: error: package io.micrometer.core.instrument does not exist
import io.micrometer.core.instrument.Gauge;

2022-03-04 12:57 UTC, pderop commented
> Task :reactor-netty-core:compileJava
/Users/pderop/Work/projects/reactor-netty-pderop/reactor-netty-core/src/main/java/reactor/netty/transport/ByteBufAllocatorMetrics.java:18: error: package io.micrometer.core.instrument does not exist
import io.micrometer.core.instrument.Gauge;
```

2022-03-04 12:58 UTC, pderop commented
it seems that the main branch does not build ? I have some compilation errors, like:

```
> Task :reactor-netty-core:compileJava
/Users/pderop/Work/projects/reactor-netty-pderop/reactor-netty-core/src/main/java/reactor/netty/transport/ByteBufAllocatorMetrics.java:18: error: package io.micrometer.core.instrument does not exist
import io.micrometer.core.instrument.Gauge;
```

2022-03-04 12:59 UTC, pderop commented
hold on, maybe I have an old snapshot in my ~/.m2/reposiry ...

2022-03-04 13:03 UTC, violetagg commented
the build on the CI is passing

2022-03-04 13:04 UTC, pderop commented
my bad, I previously compiled an older version of micrometer libraries, I'm finishing the rebase ...

2022-03-04 13:58 UTC, pderop commented
@violetagg , can you review again , I think it's now ok ? thanks

2022-03-04 15:01 UTC, violetagg requested changes

2022-03-04 15:01 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/Metrics.java
> +		REGISTRY.observationConfig().observationHandler(new ReactorNettyTimerObservationHandler(REGISTRY));
Discussed the change with @marcingrzejszczak, we should the change below


```suggestion
		REGISTRY.observationConfig()
				.observationHandler(new ObservationHandler.FirstMatchingCompositeObservationHandler(
						new ReactorNettyTimerObservationHandler(REGISTRY), new TimerObservationHandler(REGISTRY)));
```

2022-03-04 15:01 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/Metrics.java
> +import reactor.netty.observability.ReactorNettyTimerObservationHandler;
```suggestion
import io.micrometer.core.instrument.observation.ObservationHandler;
import io.micrometer.core.instrument.observation.TimerObservationHandler;
import reactor.netty.observability.ReactorNettyTimerObservationHandler;
```

2022-03-04 16:04 UTC, violetagg approved these changes

2022-03-04 16:05 UTC, violetagg commented
@simonbasle PTAL

2022-03-07 09:31 UTC, simonbasle approved these changes

2022-03-07 09:41 UTC, merged