Optimize Http2Pool by reducing calls to CLDQ size method
reactor/reactor-netty pull request #2090
Opened 2022-03-09 14:28 UTC by pderop

The PR provides an enhancement for the Http2Pool in order to reduce  _ConcurrentLinkedDeque.size()_ method calls, which is not a constant time operation. 

Indeed, it has been observed that the CLDQ size method may consume around 18% of CPU when there is a high load of http client requests while all streams are currently unavailable.

2022-03-10 10:02 UTC, simonbasle approved these changes

2022-03-11 13:05 UTC, violetagg requested changes

2022-03-11 13:05 UTC, violetagg commented on reactor-netty-http/src/main/java/reactor/netty/http/client/Http2Pool.java
> +		} else {
checkstyle: else on a new row

```suggestion
		}
		else {
```

2022-03-11 14:02 UTC, violetagg approved these changes

2022-03-11 14:20 UTC, merged