Ensure channel promises support listeners when SOCKS proxy handler is used
reactor/reactor-netty pull request #2120
Opened 2022-03-23 18:01 UTC by pderop

When a SOCKS proxy is used with a TcpClient, and when more than one message are sent **before** the tunnel is fully established with the SOCKS proxy, then the messages are buffered by the netty _ProxyHandler_ and won't be forwarded to the destination server after the tunnel is fully established.

This is because when you write multiple messages like for example this:

```
   Connection connection = TcpClient.create().proxy(spec -> spec.type(ProxyProvider.Proxy.SOCKS5)... 
   connection.outbound().sendString(Flux.just("Message1", "Message2", ...)
```

Then if the tunnel is not yet established, the netty ProxyHandler will buffer the messages using a reactor-netty _MonoSendMany.SendManyInner_ ChannelPromise, where some listeners will be added.
But, the problem is that the MonoSendMany.SendManyInner is a kind of ChannelPromise which does not support listeners, and internally, the following exception is caught (but not logged) by netty:

```
java.lang.UnsupportedOperationException
	at reactor.netty.channel.MonoSendMany$SendManyInner.addListener(MonoSendMany.java:499)
	at reactor.netty.channel.MonoSendMany$SendManyInner.addListener(MonoSendMany.java:117)
	at io.netty.util.concurrent.PromiseCombiner.add(PromiseCombiner.java:111)
	at io.netty.util.concurrent.PromiseCombiner.add(PromiseCombiner.java:97)
	at io.netty.channel.PendingWriteQueue.removeAndWriteAll(PendingWriteQueue.java:154)
	at io.netty.handler.proxy.ProxyHandler.writePendingWrites(ProxyHandler.java:427)
	at io.netty.handler.proxy.ProxyHandler.setConnectSuccess(ProxyHandler.java:296)
	at io.netty.handler.proxy.ProxyHandler.channelRead(ProxyHandler.java:259)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

The solution to this problem is to register a special handler after the netty ProxyHandler which ensures that all promises passed to the ProxyHandler are first converted to unvoid promises.

2022-03-23 18:08 UTC, pderop commented
This PR should fix rsocket/rsocket-java#1040

2022-03-24 07:15 UTC, violetagg requested changes

2022-03-24 07:15 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java
> +				}
nit: Let's fix the warnings


```suggestion
				@Override
				@SuppressWarnings("FutureReturnValueIgnored")
				public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) {
					//"FutureReturnValueIgnored" this is deliberate
					ctx.write(msg, promise.unvoid());
				}
```

2022-03-24 07:36 UTC, violetagg commented
@simonbasle @OlegDokuka  PTAL

2022-03-24 08:29 UTC, violetagg approved these changes

2022-03-24 09:23 UTC, simonbasle approved these changes

2022-03-24 15:18 UTC, OlegDokuka approved these changes
LGTM

2022-03-24 15:25 UTC, pderop commented
@violetagg , @OlegDokuka , @simonbasle , thanks for the review !

2022-03-24 15:35 UTC, merged