Add create method with metrics parameter in ConnectionProvider (#2313)
reactor/reactor-netty pull request #2314
Opened 2022-06-21 15:44 UTC by tuguri8

Add create method with name, maxConnections, metricsEnabled parameters.

Related to https://github.com/reactor/reactor-netty/issues/2313

2022-06-22 06:57 UTC, violetagg requested changes
@tuguri8 Thanks for the PR. Only one small addition that provides information in which version this method was added.

2022-06-22 06:57 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
> +	 * number of {@link Connection}
Please add

`* @since 1.0.21`

2022-06-22 07:09 UTC, violetagg commented
@tuguri8 We need to exclude this new static method from the compatibility check. Please add to `build.gradle`

```
diff --git a/reactor-netty-core/build.gradle b/reactor-netty-core/build.gradle
index 951caf774..67913b06e 100644
--- a/reactor-netty-core/build.gradle
+++ b/reactor-netty-core/build.gradle
@@ -194,6 +194,9 @@ task japicmp(type: JapicmpTask) {
 	ignoreMissingClasses = true
 	includeSynthetic = true
 	onlyIf { "$compatibleVersion" != "SKIP" }
+	methodExcludes = [
+			"reactor.netty.resources.ConnectionProvider#create(java.lang.String, int, boolean)"
+	]
 }
 
 tasks.japicmp.dependsOn(downloadBaseline)
```

2022-06-22 15:50 UTC, tuguri8 commented on reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
> +	 * number of {@link Connection}
added since tag

2022-06-22 16:23 UTC, violetagg approved these changes
@reactor/netty-team PTAL

2022-06-22 17:39 UTC, pderop approved these changes
looks good to me

2022-06-23 06:21 UTC, violetagg commented
@pderop Thanks for the review

2022-06-23 06:22 UTC, merged