Make HttpMetricsHandlerTests stable
reactor/reactor-netty pull request #2353
Opened 2022-07-04 10:23 UTC by pderop

This PR is an attempt to sabilise the HttpMetricsHandlerTests, because now in netty5, channel listeners execution is rescheduled at the end of the current event loop queue, see Netty PR [#9489 Always notify FutureListener via the EventExecutor](https://github.com/netty/netty/pull/9489)
So, this is problem for the HttpMetricsHandlerTests tests, because when we receive a response from a server, we start to verify metrics, while the metrics may be not be already up-to-date because they are updated using channel listeners, which may not be executed yet at the time we receive a response.
See for example [AbstractHttpServerMetricsHandler.java](https://github.com/reactor/reactor-netty/blob/netty5/reactor-netty-http/src/main/java/reactor/netty/http/server/AbstractHttpServerMetricsHandler.java#L122-L148)

This PR ensures that no pending tasks are currently enqueued in event loops, before decrementing test latches, see new _scheduleCoundDown_ method.

2022-07-05 10:23 UTC, pderop commented
@violetagg , please do not review for the moment. I'll finalize this PR a bit later. Now I'm working on the multipart PR.

2022-07-06 10:50 UTC, violetagg requested changes

2022-07-06 10:50 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +					return true;
This is declared `sharable`. Can we reuse one and the same instance?

2022-07-06 12:14 UTC, violetagg approved these changes

2022-07-06 12:18 UTC, pderop commented
@violetagg , thanks for the review.

2022-07-06 12:24 UTC, merged