Revise HttpMetricsHandlerTests and fix testServerConnectionsRecorder
reactor/reactor-netty pull request #2391
Opened 2022-07-18 06:48 UTC by pderop

This PR is a revamp of the HttpMetricsHandlerTests and also fixes a concurrency issue in testServerConnectionsRecorder, which sometimes fails with this exception:

```
HttpMetricsHandlerTests > testServerConnectionsRecorder(HttpProtocol[], HttpProtocol[], ProtocolSslContextSpec, ProtocolSslContextSpec, HttpProtocol) > reactor.netty.http.HttpMetricsHandlerTests.testServerConnectionsRecorder(HttpProtocol[], HttpProtocol[], ProtocolSslContextSpec, ProtocolSslContextSpec, HttpProtocol)[8] FAILED
    java.lang.AssertionError: expectation "expectNext(Hello World!)" failed (expected: onNext(Hello World!); actual: onError(reactor.netty.http.client.PrematureCloseException: Connection prematurely closed DURING response))
        at reactor.test.MessageFormatter.assertionError(MessageFormatter.java:115)
        at reactor.test.MessageFormatter.failPrefix(MessageFormatter.java:104)
        at reactor.test.MessageFormatter.fail(MessageFormatter.java:73)
        at reactor.test.MessageFormatter.failOptional(MessageFormatter.java:88)
        at reactor.test.DefaultStepVerifierBuilder.lambda$addExpectedValue$10(DefaultStepVerifierBuilder.java:509)
        at reactor.test.DefaultStepVerifierBuilder$SignalEvent.test(DefaultStepVerifierBuilder.java:2288)
        at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onSignal(DefaultStepVerifierBuilder.java:1528)
        at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onExpectation(DefaultStepVerifierBuilder.java:1476)
        at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onError(DefaultStepVerifierBuilder.java:1129)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onError(FluxHandle.java:210)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:265)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onError(FluxDoFinally.java:119)
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onError(FluxHandleFuseable.java:226)
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onError(FluxContextWrite.java:121)
        at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onError(MonoCollectList.java:114)
        at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
        at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
        at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:255)
        at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
        at reactor.netty.channel.FluxReceive.onInboundError(FluxReceive.java:450)
        at reactor.netty.channel.ChannelOperations.onInboundError(ChannelOperations.java:492)
        at reactor.netty.http.client.HttpClientOperations.onInboundClose(HttpClientOperations.java:272)
        at reactor.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:70)
        at io.netty5.channel.DefaultChannelHandlerContext.invokeChannelInactive(DefaultChannelHandlerContext.java:284)
        at io.netty5.channel.DefaultChannelHandlerContext.findAndInvokeChannelInactive(DefaultChannelHandlerContext.java:278)
        at io.netty5.channel.DefaultChannelHandlerContext.fireChannelInactive(DefaultChannelHandlerContext.java:265)
        at io.netty5.channel.ChannelHandler.channelInactive(ChannelHandler.java:213)
        at io.netty5.channel.DefaultChannelHandlerContext.invokeChannelInactive(DefaultChannelHandlerContext.java:284)
        at io.netty5.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:808)
        at io.netty5.handler.codec.http2.DefaultHttp2StreamChannel.lambda$fireChannelInactiveAndDeregister$2(DefaultHttp2StreamChannel.java:610)
        at io.netty5.util.concurrent.SingleThreadEventExecutor.runTask(SingleThreadEventExecutor.java:338)
        at io.netty5.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:361)
        at io.netty5.channel.SingleThreadEventLoop.run(SingleThreadEventLoop.java:[180](https://github.com/reactor/reactor-netty/runs/7250727386?check_suite_focus=true#step:11:181))
        at io.netty5.util.concurrent.SingleThreadEventExecutor.lambda$doStartThread$4(SingleThreadEventExecutor.java:774)
        at io.netty5.util.internal.ThreadExecutorMap.lambda$apply$1(ThreadExecutorMap.java:68)
        at io.netty5.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
Such exception can happen if the checkServerConnectionsRecorder method throws some exceptions.
So, the PR first catches any exceptions thrown from checkServerConnectionsRecorder, and then the testServerConnectionsRecorder asserts if the exception has not been thrown.

So, when doing this, we can then see the root cause exception (this exception comes from netty5 branch, bit it's the same issue in 1.0.x branch):

```
HttpMetricsHandlerTests > testServerConnectionsRecorder(HttpProtocol[], HttpProtocol[], ProtocolSslContextSpec, ProtocolSslContextSpec, HttpProtocol) > reactor.netty.http.HttpMetricsHandlerTests.testServerConnectionsRecorder(HttpProtocol[], HttpProtocol[], ProtocolSslContextSpec, ProtocolSslContextSpec, HttpProtocol)[4] FAILED
    org.opentest4j.AssertionFailedError: 
    expected: 
      null
     but was: 
      org.opentest4j.AssertionFailedError: 
      expected: 1
       but was: 0
      	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
      	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
      	at reactor.netty.http.HttpMetricsHandlerTests.checkServerConnectionsRecorder(HttpMetricsHandlerTests.java:768)
      	at reactor.netty.http.HttpMetricsHandlerTests.lambda$setUp$9(HttpMetricsHandlerTests.java:157)
      	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185)
      	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
      	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
      	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:279)
      	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:388)
      	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:408)
      	at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:579)
      	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94)
      	at io.netty5.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:437)
      	at io.netty5.channel.DefaultChannelHandlerContext.findAndInvokeChannelRead(DefaultChannelHandlerContext.java:430)
      	at io.netty5.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:411)
      	at reactor.netty.http.server.AbstractHttpServerMetricsHandler.channelRead(AbstractHttpServerMetricsHandler.java:192)
      	at io.netty5.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:437)
      	at io.netty5.channel.DefaultChannelHandlerContext.findAndInvokeChannelRead(DefaultChannelHandlerContext.java:430)
      	at io.netty5.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:411)
      	at reactor.netty.http.server.Http2StreamBridgeServerHandler.channelRead(Http2StreamBridgeServerHandler.java:142)
      	at io.netty5.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:437)
      	at io.netty5.channel.DefaultChannelHandlerContext.findAndInvokeChannelRead(DefaultChannelHa [...]

2022-08-02 15:37 UTC, pderop commented
now, it is ok.

2022-08-03 07:52 UTC, violetagg requested changes
Please keep formatting changes (when needed) in a separate change, it will be easier for the one that is reviewing the change.

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +				.verify(Duration.ofSeconds(30));
Let's do the formatting (when needed) in a separate change. Wdyt?

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +	                                  @Nullable ProtocolSslContextSpec serverCtx, @Nullable ProtocolSslContextSpec clientCtx) {
Let's do the formatting (when needed) in a separate change. Wdyt?

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +	                                  @Nullable ProtocolSslContextSpec serverCtx, @Nullable ProtocolSslContextSpec clientCtx) {
Let's do the formatting (when needed) in a separate change. Wdyt?

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> -			@Nullable ProtocolSslContextSpec serverCtx, @Nullable ProtocolSslContextSpec clientCtx) throws Exception {
Let's do the formatting (when needed) in a separate change. Wdyt?

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +				.verify(Duration.ofSeconds(30));
Let's do the formatting (when needed) in a separate change. Wdyt?

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +		// the serverCompletedHandler is used to detect when the server has sent the last response content
```suggestion
		// the requestReceivedHandler is used to detect when the server has received the last client request content
		// the responseSentHandler is used to detect when the server has sent the last response content
```

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +				.doOnConnection(cnx -> requestReceivedHandler.register(requestReceivedRef, cnx.channel().pipeline()))
Can we do this with one callback? E.g.

```suggestion
				.doOnConnection(cnx -> {
					responseSentHandler.register(responseSentRef, cnx.channel().pipeline());
					requestReceivedHandler.register(requestReceivedRef, cnx.channel().pipeline());
				})
```

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +				.verify(Duration.ofSeconds(30));
Let's do the formatting (when needed) in a separate change. Wdyt?

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +				.verify(Duration.ofSeconds(30));
Let's do the formatting (when needed) in a separate change. Wdyt?

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +				.verify(Duration.ofSeconds(30));
Let's do the formatting (when needed) in a separate change. Wdyt?

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +	                                      @Nullable ProtocolSslContextSpec serverCtx, @Nullable ProtocolSslContextSpec clientCtx) {
Let's do the formatting (when needed) in a separate change. Wdyt?

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +	                                      @Nullable ProtocolSslContextSpec serverCtx, @Nullable ProtocolSslContextSpec clientCtx) throws Exception {
Let's do the formatting (when needed) in a separate change. Wdyt?

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +				.bindNow();
Let's do the formatting (when needed) in a separate change. Wdyt?

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +				});
```suggestion
				promise.addListener(future -> latchRef.get().countDown());
```

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +		private AtomicReference<Throwable> error = new AtomicReference<>();
```suggestion
		private final AtomicReference<Throwable> error = new AtomicReference<>();
```

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +		public void channelInactive(ChannelHandlerContext ctx) throws Exception {
`Exception` is never thrown
```suggestion
		public void channelInactive(ChannelHandlerContext ctx) {
```

2022-08-03 07:52 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/HttpMetricsHandlerTests.java
> +		void register(CountDownLatch latch, ChannelPipeline pipeline) {
This method is never used?

2022-08-03 09:01 UTC, pderop commented
thanks Violeta, I have applied your suggestions, please re-take a look ?

2022-08-03 09:05 UTC, pderop commented
by the way, the error for macos-11/nio is unrelated to the changes.

2022-08-03 09:07 UTC, pderop commented
mmm, please wait, I need to check the windows error ...

2022-08-03 09:10 UTC, pderop commented
ok, the windows error is also unrelated to the changes.

2022-08-03 10:32 UTC, violetagg approved these changes

2022-08-03 11:37 UTC, pderop commented
@violetagg , thank you for your review.

2022-08-03 11:44 UTC, merged