Add documentation and examples for the integration with Micrometer Tracing
reactor/reactor-netty pull request #2558
Opened 2022-11-02 12:35 UTC by violetagg

2022-11-02 12:36 UTC, violetagg commented
@reactor/netty-team @marcingrzejszczak @Buzzardo PTAL

2022-11-02 12:51 UTC, marcingrzejszczak approved these changes
Looks fantastic!

2022-11-02 14:10 UTC, pderop approved these changes
looks good to me

2022-11-02 15:43 UTC, Buzzardo requested changes

2022-11-02 15:43 UTC, Buzzardo commented on docs/asciidoc/http-client.adoc
> +See <<observability-spans-hostname-resolution-span>>
Add a period at the end.

2022-11-02 15:43 UTC, Buzzardo commented on docs/asciidoc/http-client.adoc
> +See the https://micrometer.io/docs/tracing#_micrometer_tracing_opentelemetry_setup[`Micrometer Tracing`] documentation for `OpenTelemetry` setup if needed.
Remove `if needed`. (That's always implied with a See or See also link.)

2022-11-02 15:43 UTC, Buzzardo commented on docs/asciidoc/http-client.adoc
> +<1> Initialises Brave, Zipkin and the Observation registry.
Change `initialises` to `initializes`. (Spring uses American spelling.)

Add a comma after `Zipkin`. (Spring uses serial commas - often called the Harvard comma or the Oxford comma.)

2022-11-02 15:43 UTC, Buzzardo commented on docs/asciidoc/tcp-client.adoc
> +See the https://micrometer.io/docs/tracing#_micrometer_tracing_opentelemetry_setup[`Micrometer Tracing`] documentation for `OpenTelemetry` setup if needed.
Remove if needed. (That's always implied with a See or See also link.)

2022-11-02 15:43 UTC, Buzzardo commented on docs/asciidoc/tcp-client.adoc
> +The result in `Zipkin`:
Add `looks like` before the colon at the end. Spring avoids sentence fragments, so we need a verb (and the verb requires an object this time).

2022-11-02 15:43 UTC, Buzzardo commented on docs/asciidoc/tcp-server.adoc
> +See the https://micrometer.io/docs/tracing#_micrometer_tracing_opentelemetry_setup[`Micrometer Tracing`] documentation for `OpenTelemetry` setup if needed.
Remove if needed. (That's always implied with a See or See also link.)

2022-11-02 15:43 UTC, Buzzardo commented on docs/asciidoc/tcp-server.adoc
> +The result in `Zipkin`:
Add `looks like` before the colon at the end. Spring avoids sentence fragments, so we need a verb (and the verb requires an object this time).

2022-11-02 15:43 UTC, Buzzardo commented on docs/asciidoc/tcp-server.adoc
> +<1> Initialises Brave, Zipkin and the Observation registry.
Change initialises to initializes. (Spring uses American spelling.)

Add a comma after Zipkin. (Spring uses serial commas - often called the Harvard comma or the Oxford comma.)

2022-11-02 15:43 UTC, Buzzardo commented on docs/asciidoc/tcp-server.adoc
> +<2> Enables the built-in integration with Micrometer
Add a period at the end.

2022-11-02 15:43 UTC, Buzzardo commented on docs/asciidoc/http-server.adoc
> +<3> Enables the built-in integration with Micrometer
Add a period at the end.

2022-11-02 15:43 UTC, Buzzardo commented on reactor-netty-http-brave/README.md
> +Prefer using the standard `HttpClient/HttpServer` integration with [Micrometer Tracing](https://micrometer.io/docs/tracing).
Change `Prefer using` to `We prefer to use`.

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/http-client.adoc
> +See <<observability-spans-http-client-response-span>>
```suggestion
See <<observability-spans-http-client-response-span>>.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/http-client.adoc
> +See <<observability-spans-hostname-resolution-span>>
```suggestion
See <<observability-spans-hostname-resolution-span>>.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/http-client.adoc
> +See <<observability-spans-connect-span>>
```suggestion
See <<observability-spans-connect-span>>.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/http-client.adoc
> +See <<observability-spans-tls-handshake-span>>
```suggestion
See <<observability-spans-tls-handshake-span>>.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/http-client.adoc
> +See the https://micrometer.io/docs/tracing#_micrometer_tracing_opentelemetry_setup[`Micrometer Tracing`] documentation for `OpenTelemetry` setup if needed.
```suggestion
See the https://micrometer.io/docs/tracing#_micrometer_tracing_opentelemetry_setup[`Micrometer Tracing`] documentation for `OpenTelemetry` setup.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/http-client.adoc
> +<1> Initialises Brave, Zipkin and the Observation registry.
```suggestion
<1> Initializes Brave, Zipkin, and the Observation registry.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/http-client.adoc
> +<2> Templated URIs will be used as an URI tag value when possible
```suggestion
<2> Templated URIs are used as an URI tag value when possible.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/http-client.adoc
> +<3> Enables the built-in integration with Micrometer
```suggestion
<3> Enables the built-in integration with Micrometer.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/http-client.adoc
> +The result in `Zipkin`:
```suggestion
The result in `Zipkin` looks like:
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/http-server.adoc
> +See <<observability-spans-http-server-response-span>>
```suggestion
See <<observability-spans-http-server-response-span>>.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/http-server.adoc
> +See the https://micrometer.io/docs/tracing#_micrometer_tracing_opentelemetry_setup[`Micrometer Tracing`] documentation for `OpenTelemetry` setup if needed.
```suggestion
See the https://micrometer.io/docs/tracing#_micrometer_tracing_opentelemetry_setup[`Micrometer Tracing`] documentation for `OpenTelemetry` setup.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/http-server.adoc
> +<1> Initialises Brave, Zipkin and the Observation registry.
```suggestion
<1> Initializes Brave, Zipkin, and the Observation registry.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/http-server.adoc
> +<2> Templated URIs will be used as an URI tag value when possible
```suggestion
<2> Templated URIs are used as an URI tag value when possible.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/http-server.adoc
> +<3> Enables the built-in integration with Micrometer
```suggestion
<3> Enables the built-in integration with Micrometer.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/http-server.adoc
> +The result in `Zipkin`:
```suggestion
The result in `Zipkin` looks like:
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/tcp-client.adoc
> +See <<observability-spans-hostname-resolution-span>>
```suggestion
See <<observability-spans-hostname-resolution-span>>.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/tcp-client.adoc
> +See <<observability-spans-connect-span>>
```suggestion
See <<observability-spans-connect-span>>.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/tcp-client.adoc
> +See <<observability-spans-tls-handshake-span>>
```suggestion
See <<observability-spans-tls-handshake-span>>.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/tcp-client.adoc
> +See the https://micrometer.io/docs/tracing#_micrometer_tracing_opentelemetry_setup[`Micrometer Tracing`] documentation for `OpenTelemetry` setup if needed.
```suggestion
See the https://micrometer.io/docs/tracing#_micrometer_tracing_opentelemetry_setup[`Micrometer Tracing`] documentation for `OpenTelemetry` setup.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/tcp-client.adoc
> +<1> Initialises Brave, Zipkin and the Observation registry.
```suggestion
<1> Initializes Brave, Zipkin, and the Observation registry.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/tcp-client.adoc
> +<2> Enables the built-in integration with Micrometer
```suggestion
<2> Enables the built-in integration with Micrometer.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/tcp-client.adoc
> +The result in `Zipkin`:
```suggestion
The result in `Zipkin` looks like:
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/tcp-server.adoc
> +See <<observability-spans-tls-handshake-span>>
```suggestion
See <<observability-spans-tls-handshake-span>>.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/tcp-server.adoc
> +See the https://micrometer.io/docs/tracing#_micrometer_tracing_opentelemetry_setup[`Micrometer Tracing`] documentation for `OpenTelemetry` setup if needed.
```suggestion
See the https://micrometer.io/docs/tracing#_micrometer_tracing_opentelemetry_setup[`Micrometer Tracing`] documentation for `OpenTelemetry` setup.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/tcp-server.adoc
> +<1> Initialises Brave, Zipkin and the Observation registry.
```suggestion
<1> Initializes Brave, Zipkin, and the Observation registry.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/tcp-server.adoc
> +<2> Enables the built-in integration with Micrometer
```suggestion
<2> Enables the built-in integration with Micrometer.
```

2022-11-02 19:52 UTC, violetagg commented on docs/asciidoc/tcp-server.adoc
> +The result in `Zipkin`:
```suggestion
The result in `Zipkin` looks like:
```

2022-11-02 19:52 UTC, violetagg commented on reactor-netty-http-brave/README.md
> +Prefer using the standard `HttpClient/HttpServer` integration with [Micrometer Tracing](https://micrometer.io/docs/tracing).
```suggestion
We prefer to use the standard `HttpClient/HttpServer` integration with [Micrometer Tracing](https://micrometer.io/docs/tracing).
```

2022-11-02 20:01 UTC, violetagg commented on docs/asciidoc/http-client.adoc
> +| HTTP <HTTP METHOD> | Information and total time for the request/response.
```suggestion
| HTTP <HTTP METHOD> | Information and total time for the request.
```

2022-11-02 20:01 UTC, violetagg commented on docs/asciidoc/http-server.adoc
> +| <HTTP METHOD>_<URI> | Information and total time for the request/response.
```suggestion
| <HTTP METHOD>_<URI> | Information and total time for the request.
```

2022-11-03 08:47 UTC, violetagg commented
@marcingrzejszczak @pderop @Buzzardo Thanks for the review!

2022-11-03 08:47 UTC, merged