Support configurable DNS resolver cache
reactor/reactor-netty pull request #2622
Opened 2022-12-22 13:58 UTC by samueldlightfoot

- Support user-provided DnsCache for NameResolverProvider

2022-12-22 15:51 UTC, violetagg requested changes
Let's make JAPICMP happy

```
diff --git a/reactor-netty-core/build.gradle b/reactor-netty-core/build.gradle
index 47cf5e8b8..949b89961 100644
--- a/reactor-netty-core/build.gradle
+++ b/reactor-netty-core/build.gradle
@@ -232,6 +232,11 @@ task japicmp(type: JapicmpTask) {
 	includeSynthetic = true
 
 	compatibilityChangeExcludes = [ "METHOD_NEW_DEFAULT" ]
+
+	methodExcludes = [
+			'reactor.netty.transport.NameResolverProvider#resolveCache()',
+			'reactor.netty.transport.NameResolverProvider$NameResolverSpec#resolveCache(io.netty.resolver.dns.DnsCache)'
+	]
 }
 
 tasks.japicmp.dependsOn(downloadBaseline)
```

2022-12-22 18:40 UTC, violetagg requested changes
Thanks for the PR!

I have some small comments related to javadoc.

Can we add this configuration to the reference documentation?
https://github.com/reactor/reactor-netty/blob/main/docs/asciidoc/http-client.adoc#host-name-resolution
https://github.com/reactor/reactor-netty/blob/main/docs/asciidoc/tcp-client.adoc#host-name-resolution

2022-12-22 18:40 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
> +		 * @return {@code this}
```suggestion
		 * @return {@code this}
		 * @since 1.0.27
```

2022-12-22 18:40 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/transport/NameResolverProvider.java
> +	 * @return the configured DNS resolver cache or null
```suggestion
	 * @return the configured DNS resolver cache or null
	 * @since 1.0.27
```

2022-12-23 09:02 UTC, violetagg commented
@samueldlightfoot The last change overrides the change in the javadoc

https://github.com/reactor/reactor-netty/compare/45a29da3dc2a0c5885aad7cd798c7d6995a48ec5..5664ecbaa748f7ac73a971e9d93e34c17529c422

2022-12-23 12:11 UTC, violetagg approved these changes
@reactor/netty-team PTAL

2023-01-02 11:09 UTC, pderop approved these changes
thanks for the PR ! 
LGTM

2023-01-03 07:38 UTC, merged

2023-01-03 08:15 UTC, violetagg commented
I back ported this PR to `1.0.x` branch