Add Reactor Netty version of the Quote of the Moment example #761
reactor/reactor-netty pull request #2636
Opened 2023-01-07 19:15 UTC by jchenga

This PR attempts to provide a corresponding Reactor Netty version of the QOTM example available in Netty project.

Related to https://github.com/reactor/reactor-netty/issues/761

2023-01-13 09:58 UTC, violetagg commented
@jchenga I'm gonna check this today

2023-01-16 09:17 UTC, violetagg requested changes
@jchenga Thanks for the PR!

2023-01-16 09:17 UTC, violetagg commented on reactor-netty-examples/src/main/java/reactor/netty/examples/udp/qotm/QuoteOfTheMomentClient.java
> +				//.host(HOST)
```suggestion
```
```suggestion
				//.host(HOST)
```

2023-01-16 09:18 UTC, violetagg commented
@reactor/netty-team PTAL

2023-01-16 10:10 UTC, pderop approved these changes
looks good to me, thanks for the PR.

2023-01-16 13:35 UTC, violetagg approved these changes

2023-01-16 13:36 UTC, merged

2023-01-16 17:48 UTC, jchenga commented
> @jchenga Thanks for the PR!

No problem. Glad to be of help.