Remove FQDN from PoolKey
reactor/reactor-netty pull request #2733
Opened 2023-03-19 21:14 UTC by yuzawa-san

The SocketAddres.toString method to generate the FQDN is relatively heavy and it appears to be unnecessary given the socket address is being hashed and equaled already. This should work for unix domain sockets as well.

This code:
````java
System.out.println(AddressUtils.createUnresolved("127.0.0.1", 80));
System.out.println(AddressUtils.createUnresolved("127.0.0.1", 80).equals(AddressUtils.createUnresolved("127.0.0.1", 80)));
System.out.println(AddressUtils.createUnresolved("example.com", 80));
System.out.println(AddressUtils.createUnresolved("example.com", 80).equals(AddressUtils.createUnresolved("example.com", 80)));
System.out.println(AddressUtils.createResolved("example.com", 80));
System.out.println(AddressUtils.createResolved("example.com", 80).equals(AddressUtils.createResolved("example.com", 80)));
System.out.println(AddressUtils.createResolved("example.com", 80).equals(AddressUtils.createUnresolved("example.com", 80)));
System.out.println(UnixDomainSocketAddress.of("/tmp/mysock"));
````
prints out:
````
/127.0.0.1:80
true
example.com/<unresolved>:80
true
example.com/93.184.216.34:80
true
false
/tmp/mysock
````

before:
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/1082334/226209615-1d2d6978-06b7-4ed4-a656-b72cafecab4b.png">

and after this is basically gone
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/1082334/226209825-fa2662c4-98dc-4b4a-a548-1b4f531d76e6.png">

I also fixed up the hashCode like I did in https://github.com/reactor/reactor-netty/pull/2732

2023-03-21 03:38 UTC, yuzawa-san commented
@violetagg I set a breakpoint in the existing code when my client hits `https://en.wikipedia.org/` and `https://wikipedia.org/` and the socket (toString) is `en.wikipedia.org/<unresolved>:443`  and `wikipedia.org/<unresolved>:443` respectively

````java
System.out.println(AddressUtils.createUnresolved("wikipedia.org", 443).equals(AddressUtils.createUnresolved("en.wikipedia.org", 443)));
````
prints `false` which is expected, indicating those would go into two separate pools which is correct.

is the concern that some resolved InetSocketAddresses could be bucketed in the pool together? like weird mixtures of resolved and unresolved InetSocketAddresses or ip-address only vs hostname only InetSocketAddresses? or would it be inconsistent across different java versions? looks like it would work:  https://github.com/openjdk/jdk/blob/jdk-11%2B0/src/java.base/share/classes/java/net/InetSocketAddress.java#L112

I can post some more mixtures shortly if you need more concrete examples

2023-03-21 04:34 UTC, violetagg commented
Can you try this?

```
HttpClient client = HttpClient.create().wiretap(true);

client.remoteAddress(() -> new InetSocketAddress("wikipedia.org", 443)).get().uri("/").responseContent().aggregate().asString().block();

client.remoteAddress(() -> new InetSocketAddress("en.wikipedia.org", 443)).get().uri("/").responseContent().aggregate().asString().block();
```

https://httpwg.org/specs/rfc7540.html#reuse

2023-03-24 02:03 UTC, yuzawa-san commented
@violetagg my original traces all involved unresolved InetSocketAddresses, but the wikipedia examples are a prime example of where the resolved addresses are the same and thus equals and hashcode bucket them into the same pool key. i found a solution which only uses FQDN for tiebreaking when the InetSocketAddress has a resolved address.

this has a fast path still for the unresolved addresses coming out of the UriEndpointFactory. since those are unresolved, we can skip the fqdn and lean directly on the [equals](https://github.com/openjdk/jdk/blob/da75f3c4ad5bdf25167a3ed80e51f567ab3dbd01/src/java.base/share/classes/java/net/InetSocketAddress.java#L120-L121) and [hashcode](https://github.com/openjdk/jdk/blob/da75f3c4ad5bdf25167a3ed80e51f567ab3dbd01/src/java.base/share/classes/java/net/InetSocketAddress.java#L131-L132) of InetSocketAddress.

i also added a test case. i found that the `holder.toString()` actually did not mimic the toLowerCase behavior present in those links, so maybe that is an extra bugfix i stumbled upon. see `key3` and `key4`, those were true in the prior version of the code.

2023-03-24 11:45 UTC, violetagg requested changes
@yuzawa-san Thanks

only two small comments

2023-03-24 11:45 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
> +					// Use FDQN as a tie-breaker over IP's
```suggestion
					// Use FQDN as a tie-breaker over IP's
```

2023-03-24 11:45 UTC, violetagg commented on reactor-netty-core/src/test/java/reactor/netty/resources/PoolKeyTest.java
> +	void test() throws IllegalAccessException {
nit: Throwing `IllegalAccessException` is not needed

```suggestion
	void test() {
```

2023-03-24 11:46 UTC, violetagg commented
@reactor/netty-team PTAL

2023-03-24 13:24 UTC, pderop approved these changes
@yuzawa-san , thanks for the PR.

2023-03-27 08:46 UTC, violetagg approved these changes
Thanks

2023-03-27 08:48 UTC, merged