Configuration for setting expected number of connection pools to be created
reactor/reactor-netty pull request #3566
Opened 2024-12-29 06:51 UTC by jchenga

Introduce a configuration option to specify the expected number of connection pools a ConnectionProvider should create. Once the expected number is exceeded, a warning message is logged.

2024-12-30 09:03 UTC, violetagg requested changes

2024-12-30 09:03 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
> +import org.mockito.Mock;
Unused import

```suggestion
```

2025-01-03 10:26 UTC, violetagg requested changes
@jchenga Thanks for the PR!
I do have some suggestions for the name of the new API and for the tests.

2025-01-03 10:26 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
> +	final int expectedConnectionPools;
IMO it is better to call it maximum connection pools. Wdyt?

```suggestion
	final int maxConnectionPools;
```

2025-01-03 10:26 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
> +		this.expectedConnectionPools = builder.expectedConnectionPools;
IMO it is better to call it maximum connection pools. Wdyt?

```suggestion
		this.maxConnectionPools = builder.maxConnectionPools;
```

2025-01-03 10:26 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/resources/PooledConnectionProvider.java
> +								expectedConnectionPools);
IMO it is better to call it maximum connection pools. Wdyt?

```suggestion
				if (maxConnectionPools > Builder.MAX_CONNECTION_POOLS && connectionPoolCount.incrementAndGet() > maxConnectionPools) {
					if (log.isWarnEnabled()) {
						log.warn("Connection pool creation limit exceeded: {} pools created, maximum expected is {}", connectionPoolCount.get(),
								maxConnectionPools);
```

2025-01-03 10:26 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
> +		ConnectionProvider connectionProvider = ConnectionProvider.builder("expected-connection-pool").expectedConnectionPools(1).build();
IMO it is better to call it maximum connection pools. Wdyt?

```suggestion
		ConnectionProvider connectionProvider = ConnectionProvider.builder("max-connection-pools").maxConnectionPools(1).build();
```

2025-01-03 10:26 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
> +		ConnectionProvider connectionProvider = ConnectionProvider.builder("expected-connection-pool").build();
```suggestion
		ConnectionProvider connectionProvider = ConnectionProvider.builder("max-connection-pools").build();
```

2025-01-03 10:26 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
> +	@Test
IMO we can simplify these tests with using `@ParameterizedTest`

Something like the snippet below. Wdyt?

```
@ParameterizedTest
@ValueSource(booleans = {true, false})
void maxConnectionPools(boolean withMaxConnectionPools) throws SSLException {

...
		ConnectionProvider connectionProvider = withMaxConnectionPools ?
				ConnectionProvider.builder("max-connection-pool").maxConnectionPools(1).build() :
				ConnectionProvider.builder("max-connection-pool").build();
...

}
```

2025-01-03 10:26 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
> +		Loggers.resetLoggerFactory();
Please ensure you reset in finally block.

2025-01-04 04:06 UTC, jchenga commented on reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
> +		static final int EXPECTED_CONNECTION_POOLS_DISABLED = -1;
I named it "expected connection pools" to clarify that this setting is not a strict maximum, as the term "max connection pools" might imply a limit on the number of connections that can be created. this is not the case because we only log a warning message and still proceed to create a connection pool.

I'm open to calling it "max connection pools" though. since this term makes it easier to alter the behavior in the future, such as throwing exceptions when this threshold is surpassed. it'd be very confusing if we call it "expected connection pool" and throw an exception when the threshold is exceeded.

2025-01-04 07:35 UTC, jchenga commented on reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
> +		Loggers.resetLoggerFactory();
sounds good. I'll go ahead and make all the suggested changes.

2025-01-04 08:42 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
> +		static final int EXPECTED_CONNECTION_POOLS_DISABLED = -1;
Yes this is my intention - start with warning in this version and in the next version start throwing an exception.

2025-01-04 19:43 UTC, jchenga commented
I have made the suggested changes.

2025-01-06 08:42 UTC, violetagg requested changes

2025-01-06 08:42 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
> +		 * The value must be positive or zero; otherwise, the connection pools check is ignored.
Why do we want to allow this value to be set to `0`? If one doesn't want pooling, one can disable the pooling.

2025-01-06 08:42 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
> +			this.maxConnectionPools = maxConnectionPools;
Please add a check for the provided value.

2025-01-06 08:42 UTC, violetagg commented on reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
> +			this.maxConnectionPools = maxConnectionPools;
Do we want the user to be able to reset this to `-1`? For example:

https://github.com/reactor/reactor-netty/blob/11f91b04c960286fffba0ab90e56e91440350f67/reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java#L585-L602

2025-01-06 08:42 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
> +			disposableServer.dispose();
Let's dispose the `ConnectionProvider` here.
No need to dispose the server it will be disposed by `reactor.netty.BaseHttpTest#disposeServer`

2025-01-08 00:57 UTC, jchenga commented on reactor-netty-core/src/main/java/reactor/netty/resources/ConnectionProvider.java
> +		 * The value must be positive or zero; otherwise, the connection pools check is ignored.
no particular reason really. it's a leftover from the original "expected connection pool" setting. as in, i expect 0 connection pool and show me a warning message if one is created. 

I will make all the suggested changes.

2025-01-08 07:42 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
> +			Loggers.resetLoggerFactory();
```suggestion
			Loggers.resetLoggerFactory();
			connectionProvider.dispose();
```

2025-01-08 08:19 UTC, violetagg commented on reactor-netty-http/src/test/java/reactor/netty/http/client/HttpClientTest.java
> +			Loggers.useCustomLoggers(s -> spyLogger);
```suggestion
		Logger spyLogger = Mockito.spy(log);
		Loggers.useCustomLoggers(s -> spyLogger);

		ConnectionProvider connectionProvider = withMaxConnectionPools ? ConnectionProvider
				.builder("max-connection-pools")
				.maxConnectionPools(1)
				.build() : ConnectionProvider
				.builder("max-connection-pools")
				.build();

		try {
			ArgumentCaptor<String> argumentCaptor = ArgumentCaptor.forClass(String.class);
```

2025-01-08 09:29 UTC, violetagg approved these changes
@jchenga Thanks for the PR!

2025-01-08 09:54 UTC, merged