Supports configurable compression level
reactor/reactor-netty pull request #3567
Opened 2024-12-29 08:10 UTC by raccoonback

## Motivation
Hello,

I have added a feature to support compression level configuration in Reactor Netty's `SimpleCompressionHandler`.

Feature Details:
- Compression methods such as gzip, deflate, zstd now allow specifying the compression level.
- For brotli and snappy, since it does not support compression level configuration, the existing default behavior remains unchanged.

This enhancement is expected to enable users to better balance compression efficiency and performance.

Thanks.

## Issue
- Previously closed Pull-Request: https://github.com/reactor/reactor-netty/pull/3565
- Fixs: https://github.com/reactor/reactor-netty/issues/3244

2025-01-01 15:17 UTC, raccoonback commented on reactor-netty-http/src/main/java/reactor/netty/http/server/SimpleCompressionHandler.java
> -		super((CompressionOptions[]) null);
Remove unnecessary constructors

2025-01-01 15:17 UTC, raccoonback commented on reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
> +			super(c, listener, nettyRequest, null, HttpCompressionSettingsSpec.provideDefault(), connectionInfo,
Specifies the default compression level supported for each compression.
- gzip, deflate: 6
- zstd: 3

2025-01-01 15:17 UTC, raccoonback commented on reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java
> +			SimpleCompressionHandler handler = SimpleCompressionHandler.create(compressionSettings);
Applies the user-defined `compression settings` to the Netty's compression settings.

2025-01-01 15:17 UTC, raccoonback commented on reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServer.java
> +	}
This method takes compression settings from the user.

2025-01-01 15:17 UTC, raccoonback commented on reactor-netty-http/src/main/java/reactor/netty/http/server/HttpCompressionSettingsSpec.java
> +}
Defines a spec for configuring HTTP compression.

2025-01-01 15:17 UTC, raccoonback commented on reactor-netty-http/src/main/java/reactor/netty/http/server/HttpCompressionSettingsSpec.java
> +	private ZstdOptions zstdOptions;
Compression settings supported by Netty.

2025-01-01 15:17 UTC, raccoonback commented on reactor-netty-http/src/main/java/reactor/netty/http/server/HttpCompressionSettingsSpec.java
> +	}
The `default constructor` sets the available compression to **default settings**.

2025-01-01 15:17 UTC, raccoonback commented on reactor-netty-http/src/main/java/reactor/netty/http/server/HttpCompressionSettingsSpec.java
> +	}
Initializes to each compression setting entered by the Builder.

2025-01-01 15:17 UTC, raccoonback commented on reactor-netty-http/src/main/java/reactor/netty/http/server/HttpCompressionSettingsSpec.java
> +	}
Adapts to the type to be provided to the constructor argument of Netty's [`HttpContentCompressor`](https://github.com/netty/netty/blob/bbf3efec982d9eb22cc8ca433b17ec052cb76d59/codec-http/src/main/java/io/netty/handler/codec/http/HttpContentCompressor.java#L160-L162).

2025-01-01 15:17 UTC, raccoonback commented on reactor-netty-http/src/main/java/reactor/netty/http/server/HttpCompressionSettingsSpec.java
> +	}
A builder that takes each compression setting as input from the user.

2025-01-01 15:17 UTC, raccoonback commented on reactor-netty-http/src/main/java/reactor/netty/http/server/Http3Codec.java
> +			p.addLast(NettyPipeline.CompressionHandler, SimpleCompressionHandler.create(compressionSettings));
Apply the configured compression settings.

2025-01-03 10:42 UTC, violetagg commented on reactor-netty-http/src/main/java/reactor/netty/http/server/HttpCompressionSettingsSpec.java
> +		Builder gzip(int compressionLevel);
@raccoonback If in the future you need to extend the configuration API with `window Bits`, `memory level` etc. How will we introduce them?

2025-01-03 11:59 UTC, raccoonback commented on reactor-netty-http/src/main/java/reactor/netty/http/server/HttpCompressionSettingsSpec.java
> +		Builder gzip(int compressionLevel);
@violetagg 
Thank you for the great question! 

The reason why `windowBits` and `memoryLevel` are not currently configurable is that their default settings in GZIP are optimized for most use cases. Exposing these options could lead to unnecessary increases in memory usage or make configuration overly complex.

For now, we’ve chosen to rely on default values without exposing these settings directly to users. However, we’ve considered the need for extensibility in future requirements.

If it becomes necessary to make `windowBits` and `memoryLevel` configurable, the API can be extended using with **method overloading**:

```java

Builder gzip(int compressionLevel);

Builder gzip(int compressionLevel, int windowBits);

Builder gzip(int compressionLevel, int windowBits, int memoryLevel);

// ...

```

Additionally, if required, we can extend the API to provide these as optional settings while maintaining the default values. Let me know your thoughts, and I’ll adjust the design accordingly.

2025-01-06 08:50 UTC, violetagg commented on reactor-netty-http/src/main/java/reactor/netty/http/server/HttpCompressionSettingsSpec.java
> +		Builder gzip(int compressionLevel);
Mmm ... method overloading is not something that I would like to see in the API. Can use a similar approach to Netty's `CompressionOptions`

2025-01-09 07:47 UTC, violetagg requested changes

2025-01-09 07:47 UTC, violetagg commented on reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
> +		this.compressionOptions = HttpCompressionOptionsSpec.provideDefault();
Can we not initialise this with a default, or maybe it can be empty? The default will be used only when the compression is enabled. In Reactor Netty we try to not initialise things that will not be used.

2025-01-09 12:55 UTC, raccoonback commented on reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java
> +		this.compressionOptions = HttpCompressionOptionsSpec.provideDefault();
@violetagg 
Thank you for the suggestion!
I’ve updated the implementation in commit c28d954 to set compressionOptions to null as the default state when compression is disabled.

2025-01-10 10:18 UTC, violetagg commented on reactor-netty-http/src/main/java/reactor/netty/http/server/compression/DeflateOption.java
> +	DeflateOption(int compressionLevel, int windowBits, int memoryLevel) {
I imagined some kind of a builder because I don't see how this is different than what was before.

2025-01-10 10:59 UTC, raccoonback commented on reactor-netty-http/src/main/java/reactor/netty/http/server/compression/DeflateOption.java
> +	DeflateOption(int compressionLevel, int windowBits, int memoryLevel) {
Thank you for the feedback!
In this PR, I have implemented the compression settings to only be configurable via the methods provided by `StandardHttpCompressionOptions`.

```java
HttpServer.create()
	.compress(true)
	.compressOptions(
	    StandardHttpCompressionOptions.gzip(6, 15, 8),
            StandardHttpCompressionOptions.zstd(12, 65536, 65536)
	)
	.bindNow();
```

By Builder approach, did you mean a method where each compression setting is handled through chainable calls, as shown below? 😊

```java
HttpServer.create()
	.compress(true)
	.compressOptions(
           GzipOptions.builder()
                         .compressionLevel(6)
                         .windowBits(15)
                         .windowBits(8)
                         .build(),
           ZstdOptions.builder()
                         .compressionLevel(12)
                         .blockSize(65536)
                         .maxEncodeSize(65536)
                         .build()
	)
	.bindNow();
```

2025-01-10 11:20 UTC, violetagg commented
Yes, basically if you want to configure compression level, you configure
only this the rest stays the default and if in the future we need to add
something else then we just add only this new configuration to the builder

On Fri, 10 Jan 2025 at 13:00, KOSEUNGBIN ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> reactor-netty-http/src/main/java/reactor/netty/http/server/compression/DeflateOption.java
> <https://github.com/reactor/reactor-netty/pull/3567#discussion_r1910211492>
> :
>
> > +import io.netty.handler.codec.compression.StandardCompressionOptions;
> +
> +/**
> + * Deflate compression option configuration.
> + *
> + * @author raccoonback
> + */
> +final class DeflateOption implements HttpCompressionOption {
> +
> +	private final CompressionOptions option;
> +
> +	DeflateOption() {
> +		this.option = StandardCompressionOptions.gzip();
> +	}
> +
> +	DeflateOption(int compressionLevel, int windowBits, int memoryLevel) {
>
> Thank you for the feedback!
> In this PR, I have implemented the compression settings to only be
> configurable via the methods provided by StandardHttpCompressionOptions.
>
> HttpServer.create()
> 	.compress(true)
> 	.compressOptions(
> 	    StandardHttpCompressionOptions.gzip(6, 15, 8),
>             StandardHttpCompressionOptions.zstd(12, 65536, 65536)
> 	)
> 	.bindNow();
>
> By Builder approach, did you mean a method where each compression setting
> is handled through chainable calls, as shown below? 😊
>
> HttpServer.create()
> 	.compress(true)
> 	.compressOptions(
>            GzipOptions.builder()
>                          .compressionLevel(6)
>                          .windowBits(15)
>                          .windowBits(8)
>                          .build(),
>            ZstdOptions.builder()
>                          .compressionLevel(12)
>                          .blockSize(65536)
>                          .maxEncodeSize(65536)
>                          .build()
> 	)
> 	.bindNow();
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/reactor/reactor-netty/pull/3567#discussion_r1910211492>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFKCVM43LJ5NXQ35WPOMGD2J6R4FAVCNFSM6AAAAABUKSI4SKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKNBSGE2TKNZUGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-01-10 11:29 UTC, raccoonback commented
@violetagg 
I understand!
Then, I will modify the compression settings to be configurable using the builder pattern as you suggested and request the review again.
Thank you for your feedback.

```java
HttpServer.create()
	.compress(true)
	.compressOptions(
           GzipOptions.builder()
                .compressionLevel(6)
                .windowBits(15)
                .windowBits(8)
                .build(),
           ZstdOptions.builder()
                .compressionLevel(12)
                .blockSize(65536)
                .maxEncodeSize(65536)
                .build()
	)
	.bindNow();
```

2025-01-10 15:55 UTC, raccoonback commented
@violetagg 
I have updated the implementation to reflect the Builder approach you suggested. ([99287f4](https://github.com/reactor/reactor-netty/pull/3567/commits/99287f45906b75cf76ca0e7818d09b6edc40d8b2))
Please take a look and let me know if there are any further adjustments needed!

2025-01-28 11:20 UTC, violetagg approved these changes
Thanks!

2025-01-28 11:22 UTC, merged